name: Unit tests
permissions:
   contents: read

'on': push

jobs:
   tests:
      runs-on: ubuntu-latest
      name: go test
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-go@v5
           with:
               go-version: '1.24.4'
               check-latest: true
         - run: sudo apt-get update && sudo apt-get install -y xorg-dev libgl1-mesa-dev
         - run: go test -v ./...
